<?php
/** @var $viewModel \MageModule\Magento_CategoryLinks\ViewModel\CategoryLinksUrl */

$viewModel = $block->getViewModel();

?>

<div class="category-sidebar">
    <?php

    $subcategories=$viewModel->getSubCat();

    if($subcategories->count()>0){
    ?>
    <h3><?= $block->escapeHtml(__('Categories:')) ?></h3>
    <ul class="list-category">
        <?php
        foreach($subcategories as $subcategory){

            ?>

            <li class="children-category">
                <a href="<?= $block->escapeUrl($this->getBaseUrl().$subcategory->getRequestPath()) ?>">
                    <?= $block->escapeHtml($subcategory->getName()) ?>
                </a>
            </li>

            <?php
        }

        }
        ?>
</div>
